---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: grafana
  namespace: monitoring
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - name: grafana
          containerPort: 3000
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests: 
            memory: "500Mi"
            cpu: "250m"
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: task-grafana-volume
            readOnly: false
          - mountPath: /etc/grafana/provisioning/datasources
            name: grafana-datasources
            readOnly: false
      securityContext:
        fsGroup: 472
      volumes:
        - name: grafana-datasources
          configMap:
              defaultMode: 420
              name: grafana-datasources
        - name: task-grafana-volume
          persistentVolumeClaim:
            claimName: grafana-volume-claim   
        
