---
apiVersion: v1
kind: Service

metadata:
  name: haproxy
  namespace: haproxy
  annotations:
    metallb.universe.tf/address-pool: webserver-ips
    
spec:
  selector:
    app: haproxy
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer