---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-stats
  namespace: haproxy
spec:
  selector:
    app: haproxy
  ports:
    - name: stats
      protocol: TCP
      port: 1024
      targetPort: 1024